In [3]:
%%sh
wget -N https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip
unzip -o bank-additional.zip

sh: 2: unzip: not found

CalledProcessError: Command 'b'# wget -N https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip\nunzip -o bank-additional.zip\n'' returned non-zero exit status 127.

In [4]:
import pandas as pd

data = pd.read_csv('./bank-additional/bank-additional-full.csv', sep=';')
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 50)
data[:10]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,198,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,139,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,217,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,380,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,50,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [5]:
import numpy as np

train_data, test_data, _ = np.split(data.sample(frac=1, random_state=123),
                                   [int(0.95 * len(data)), int(len(data))])

# Save to CSV files
train_data.to_csv('automl-train.csv', index=False, header=True, sep=',')     # Need to keep column names
test_data.to_csv('automl-test.csv', index=False, header=True, sep=',')

In [6]:
%%sh
ls -l *.csv

-rw-r--r-- 1 root root  257339 Jul 18 11:57 automl-test.csv
-rw-r--r-- 1 root root 4889516 Jul 18 11:57 automl-train.csv

In [7]:
import sagemaker

prefix = 'sagemaker/DEMO-automl-dm/input'
sess = sagemaker.Session()

uri = sess.upload_data(path='automl-train.csv', key_prefix=prefix)
print(uri)

s3://sagemaker-us-east-1-556463194331/sagemaker/DEMO-automl-dm/input/automl-train.csv